[phases.setup]
nixPkgs = ["nodejs_20", "npm-9_x", "python3", "python3Packages.pip"]

[phases.install]
cmds = [
    "npm ci",
    "cd manual-purchase-agent_20250513_125500_v15.6 && pip install -r requirements.txt || echo 'No requirements.txt found'"
]

[start]
cmd = "chmod +x start-railway.sh && ./start-railway.sh"