[phases.setup]
nixPkgs = ["nodejs_20", "npm-9_x", "python3", "python3Packages.pip", "python3Packages.setuptools", "python3Packages.wheel"]

[phases.install]
cmds = [
    "npm ci",
    "pip install --upgrade pip setuptools wheel",
    "cd manual-purchase-agent_20250513_125500_v15.6 && pip install -r requirements.txt"
]

[start]
cmd = "chmod +x start-railway.sh && ./start-railway.sh"